added necessary components
sakshambhatt/eklavya pull request #1
Opened 2021-03-26 20:51 UTC by sakshambhatt

Please review my component library and provide feedback.
Thanks!

2021-03-27 08:19 UTC, ishanjirety commented
![image](https://user-images.githubusercontent.com/62433518/112714973-3e6df700-8f03-11eb-82c5-0b18541517d0.png)

**You should never use uppercase letters to create classes.**
Other things look good to me

2021-03-28 21:02 UTC, AnkitKarnAK commented
Hey Saksham
Add `cursor: pointer` property on primary button

2021-03-29 11:04 UTC, sakshambhatt commented
Hello, I have changed all the class names to lowercases. Thanks for reviewing @ishanjirety .
I tried to use `cursor: pointer` in button, but it did not work. I referred [this stackoverflow answer](https://stackoverflow.com/questions/18434626/why-is-cursorpointer-effect-in-css-not-working/44510398), and yet I could not do it @AnkitKarnAK

2021-03-30 09:58 UTC, sakshambhatt commented
Hi @AnkitKarnAK , `cursor: pointer` is working now. I have not changed anything. I don't know what happened, but it is working now. Thanks for reviewing.

2021-04-02 08:00 UTC, saisumanthkacham requested changes

2021-04-02 08:00 UTC, saisumanthkacham commented on css/prism.css
> + */
Remove the unwanted code here and no suggestions in code review, everything looks good and descriptive and I love your codebase its clean.

2021-04-02 08:00 UTC, saisumanthkacham commented on css/prism.css
> +	font-size: 1em;
Ignore the selected lines as I am writing here Ui review
1.Your implementation of the minimal design can be appreciated here @sakshambhatt 
2.the hover state of links on the sidebar and navbar should be changed (remove text-decoration and change the hover state colour)
3.The position of the sidebar should be fixed to improve the user experience.
4.The place at the logo is junky, change the things around it.

2021-05-23 17:37 UTC, sakshambhatt commented on css/prism.css
> +	font-size: 1em;
Thank you for your kind review. I have finally gotten around to actually take your advice. Please take a look @saisumanthkacham.

2021-10-28 08:57 UTC, merged